### ISSUE TITLE
Cache the editorconfig instances in AbstractEditorConfigManager#getOptions 

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/ec4j#24]
The AbstractEditorConfigManager#getOptions load editorconfig instance. To have better performance, those editorconfig instance should be store in cache and cache should be updated when file changes (a simple solution is to use last modified if File).

@ppalaga what do you think about cache?

**Comment by ppalaga** [comment]
> what do you think about cache?

I wanted to propose it since I have seen your code for the first time :-)

My use case is a bit simpler than yours. I assume your `EditorConfigManager` instances will live as long as IDE is running. That's why you need the cache invalidation. 

My `EditorConfigManager` instances will live only during the execution of my plugin. My plugin checks the complete source tree and I think I can assume that, during the processing, no changes will happen in the source tree. 

Hence, to satisfy both yours and mine requirements, I propose to introduce a pluggable `CacheEntryValidator`. 

Mine would be as trivial as 

```
class ForeverValid implements CacheEntryValidator {
    boolean validate(EditorConfig entry) {
        return true;
    }
}
```

While yours would be something like

```
class ChangeExpiry implements CacheEntryValidator {
    boolean validate(EditorConfig entry) {
        return entry.getLoadTime() > entry.getLastModifiedTime();
    }
}
```

WDYT?

**Comment by angelozerr** [comment]
Very good idea!

**Comment by ppalaga** [comment]
This can closed, I think. After https://github.com/angelozerr/ec4j/pull/32 was merged, users can pass a cache to an `EditorConfigSession`.

**Comment by angelozerr** [comment]
Right!
